### ISSUE TITLE
How do I deploy contract with _initialValue?

### ISSUE THREAD

**Issue by cynic-1** [OpenAtomFoundation/xupercore#445]
I saw an example in /xupercore/kernel/evm/eth_bench_test testing evm contract deployment and invokement. However, there is no example showing us how to deploy a contract with a _initialValue.

I will appreciate it if you show me how to do that.

**Comment by godeamon** [comment]
https://github.com/xuperchain/xuper-sdk-go/blob/master/example/contract/contract.go

**Comment by godeamon** [comment]
https://xuper.baidu.com/n/xuperdoc/v5.3/advanced_usage/contract_management.html

**Comment by cynic-1** [comment]
> https://github.com/xuperchain/xuper-sdk-go/blob/master/example/contract/contract.go

Thanks for your reply.
However, I am trying to use xupercore to deploy contract. According to your documents, xuperchain was developed based on xupercore. If the contract deployment doesn't involve xupercore project, please let me know so I don't have to check xupercore anymore.

感谢回复。
但是我希望使用xupercore中的代码部署合约。根据你们的文档，xuperchain是基于xupercore开发的。如果xuper-sdk-go合约部署部分不涉及到xupercore，麻烦告知我，我以后就不用看xupercore的代码了。

**Comment by godeamon** [comment]
如果你想只是想部署合约，可以使用 xuper-sdk-go，这个是 XuperChain 的 SDK。xuper-sdk-go 也依赖了 xupercore，主要是用来发送交易，根据接口构造交易。

**Comment by DhruvHax** [comment]
Hello can we connect ? 
I had a lot of queries to ask ? 
As im working for a final year project

**Comment by godeamon** [comment]
> Hello can we connect ? I had a lot of queries to ask ? As im working for a final year project

Hello, if you have any questions, you can submit an issue or join our WeChat group.
